### ISSUE TITLE
1122 1일 차 - html, css 실습

### ISSUE THREAD

**Issue by mgm9458** [mgm9458/goorm-practice#1]
## 알게된 점

**VSC에서 커밋**

- 커밋 메세지를 작성해야 커밋할 수 있음

---

## 진행 상황

프로필 작업 링크 : https://mgm9458.github.io/goorm-practice/1122-profile1/

- VSC를 이용하여 프로필 제작 후 커밋 완료
- 피그마 디자인 후 html 작업 중

---
![image](https://github.com/user-attachments/assets/2497497b-e3cf-4f45-9af1-29c769132474)

**Comment by RunaUXLabs** [comment]
오 첫번째 쿠로미있는 프로필이 많이 업데이트 되었군요!
조금씩 스타일 적용하면서 이뻐지는 페이지를 보면서
욕심이 샘솟기를🤩
