### ISSUE TITLE
1126 3일 차 - js 키오스크 easy

### ISSUE THREAD

**Issue by mgm9458** [mgm9458/goorm-practice#3]
## 강사님 클론코딩

https://mgm9458.github.io/goorm-practice/1126-script

js는 코딩테스트 풀때 말고는 처음 다뤄보는 것이라서
강사님 기본 코딩가지고 뜯어보면서 이해하는 시간을 가졌다

## 주요 활동
![스크린샷 2024-11-26 17 19 51](https://github.com/user-attachments/assets/f66d5f2d-7865-4917-9529-97968aa07557)

모르는 메서드들이나 쓰이는 것 중 모르는 단어 위주로 필기하였다

![image](https://github.com/user-attachments/assets/818b7c88-9ca8-4ded-8814-c1a1c106f8c7)

코딩을 한 줄 한 줄 뜯어가면서 이해하고 해석하는 과정을 먼저 거치는 것이 중요하다고 생각해서
주석으로 달면서 이해하려고 했다!

**Comment by RunaUXLabs** [comment]
오 한줄한줄 주석을 달아가면서 해석하기! 제가 바라는 방식입니다(굿굿)!!!👏
지금은 주석이 많을지언정, 익숙해 지면 주석을 매번 달지 않아도 덩어리의 내부 흐름이 한눈에 보이게 될거예요.
내일 더 디테일하게 해체쇼를 하면서 파고들어 봅시다!
