### ISSUE TITLE
1127 4일 차 - 키오스크 디벨롭

### ISSUE THREAD

**Issue by mgm9458** [mgm9458/goorm-practice#4]
## 구현 화면
https://mgm9458.github.io/goorm-practice/1127-kiosk

![스크린샷 2024-11-27 17 21 01](https://github.com/user-attachments/assets/d296bf3b-ec67-4d0c-96c3-b0be3a150bb4)

### VSCode 한땀 한땀 장인 정신의 주석
![스크린샷 2024-11-27 17 23 51](https://github.com/user-attachments/assets/16e59a22-7382-41e9-99bd-3eed3a81e925)
### 노션 필기
![스크린샷 2024-11-27 17 31 13](https://github.com/user-attachments/assets/41eb58af-9b23-4965-9633-0d9304fd35e7)
![스크린샷 2024-11-27 17 32 22](https://github.com/user-attachments/assets/4b09ab1e-d066-424e-85ce-a5489233efe5)

- 역시나 아직은 보자마자 이해할 수는 없는 법..!
- 한 줄 한 줄 뜯어보며 이해하려고 노력하였고 어제보다 요소가 많아져서 시간이 더 오래걸렸던 것 같다
- 강사님 키오스크를 클론하면서 css에서 배경이나, 폰트 크기나, 컬러 요소들만 수정했다
- js 파일 자체를 이해하는 것에 목적을 두었던 것 같고 어제 좀 분석해봤다고 같은 맥락들은 그래도 금방금방 넘어갔던 것 같다(어제보단....?ㅎ)
- 현재 키오스크에서 디벨롭하는 작업도 해보고 싶다
- 채찍이와 티키타카 생각보다 재밌을지도...?

**Comment by RunaUXLabs** [comment]
계속 난이도가 올라가는 소스를 읽어보고 주석을 달면서 차근차근 전진하다보면 이제 눈으로 봐도 무슨일을 하는 앤지 알게 될거예요!
내가 원하는 기능을 넣고 싶어 소스를 채찍이한테 달라고 할 수 있지만, 내가 해석하지 못한다면 무슨소용이겠어요 ㅎㅎㅎ
꼼꼼하게 보면서 디벨롭하는 그날까지 가보자고!🙌

**Comment by KwanLee1129** [comment]
와 꼼ㅁ꼼한 주석... 짱인데요 장인 정신이 빛을 발하리라 생각합니다 👍
