### ISSUE TITLE
1128 5일 차 - react1

### ISSUE THREAD

**Issue by mgm9458** [mgm9458/goorm-practice#5]
## 문제상황
> 터미널로 여는 상황에서 Syntax Error가 났다..!

![스크린샷 2024-11-28 11 08 50](https://github.com/user-attachments/assets/8390608f-6e0d-4a43-bc1f-f9181b2b44da)

채찍이를 통해서 오류가 왜 났는지 알게되었고 그 오류는 
constants라는 이름으로 export 항목이 없어서 나는 오류였다

## 해결 방법
현재 나의 Node.js 버전이 해당 기능을 지원하지 않았기 때문에 
문제가 일어났던 것 (내 버전은 v16.13.0 ㅎ)
터미널에서 명령어로 18버전으로 업데이트 후 재시도 하였더니 문제가 해결되었고
서버까지 제대로 작동하였다

## 진행 과정

![image](https://github.com/user-attachments/assets/5a57d9e0-fc56-4a26-af73-44498566ad1c)

채찍이랑 심오한 토론을 해가며 내 작업을 만드는데에 집중하기 보다
먼저 이해하는 데에 집중하였다

제일 어려운 것 같다...............................

**Comment by RunaUXLabs** [comment]
주석이 아주 디테일하네요! 햅격!
어렵지만.... 오늘도 지식이 늘었길 바라면서...!
내일 컴포넌트와 전달에 대해 배우면 좀 더 재밌어질거라고 장담합니다😉
