### ISSUE TITLE
1129 6일 차 - React Counter 연습

### ISSUE THREAD

**Issue by mgm9458** [mgm9458/goorm-practice#6]
![스크린샷 2024-11-29 17 03 56](https://github.com/user-attachments/assets/b1504a7b-c34e-4684-9b8b-21973b3c7bc7)

## 진행 상황

![스크린샷 2024-11-29 17 18 53](https://github.com/user-attachments/assets/8fc513bc-6ad5-4b76-b09d-bc528cba9cb3)

## Issue
- 채찍이와 대화하면서 거의 마이 티처가 되었다
- Counter가 어떻게 동작하는지 어떻게 구동하는 지에 대해서 
어제보다는 좀 더 알게되었다
- 탭의 favicon 변경
- 간단한 CSS 변경
- useState에 대해 강사님 수업과 찾아본 자료들을 정리하였다
- 이번 주 주말이 나에게는 관건이라 물 밀듯 쏟아진 정보들을 기초부터 다시 넣어야겠다ㅠㅠ

**Comment by RunaUXLabs** [comment]
진짜 이번 수업에서 채찍이 덕분에 코드 디깅하고, 포기하지 않고 이것저것 시도하면서 나름의 재미들을 찾는 것 같아요.
저보다 채찍이가 편할거고, 채찍이로도 안되면 절 찾아올텐데.. 보통은 해결이 되니까...(외롭)😹
